<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<meta http-equiv="x-ua-compatible" content="IE=edge"/>
<title>Test results - Class Running an Async Task</title>
<link href="../css/base-style.css" rel="stylesheet" type="text/css"/>
<link href="../css/style.css" rel="stylesheet" type="text/css"/>
<script src="../js/report.js" type="text/javascript"></script>
</head>
<body>
<div id="content">
<h1>Class Running an Async Task</h1>
<div class="breadcrumbs">
<a href="../index.html">all</a> &gt; 
<a href="../packages/default-package.html">default-package</a> &gt; Running an Async Task</div>
<div id="summary">
<table>
<tr>
<td>
<div class="summaryGroup">
<table>
<tr>
<td>
<div class="infoBox" id="tests">
<div class="counter">3</div>
<p>tests</p>
</div>
</td>
<td>
<div class="infoBox" id="failures">
<div class="counter">2</div>
<p>failures</p>
</div>
</td>
<td>
<div class="infoBox" id="ignored">
<div class="counter">0</div>
<p>ignored</p>
</div>
</td>
<td>
<div class="infoBox" id="duration">
<div class="counter">2.034s</div>
<p>duration</p>
</div>
</td>
</tr>
</table>
</div>
</td>
<td>
<div class="infoBox failures" id="successRate">
<div class="percent">33%</div>
<p>successful</p>
</div>
</td>
</tr>
</table>
</div>
<div id="tabs">
<ul class="tabLinks">
<li>
<a href="#tab0">Failed tests</a>
</li>
<li>
<a href="#tab1">Tests</a>
</li>
<li>
<a href="#tab2">Standard output</a>
</li>
</ul>
<div id="tab0" class="tab">
<h2>Failed tests</h2>
<div class="test">
<a name="executing CalcSquareAsyncTask via executor"></a>
<h3 class="failures">executing CalcSquareAsyncTask via executor</h3>
<span class="code">
<pre>java.lang.AssertionError: expected: a value that is equal to &quot;level=INFO, message=Started CalcSquareAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Calculating square of 9, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Running Future for CalcSquareAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Completed Future for CalcSquareAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx&quot;
but was: &quot;level=INFO, message=Started CalcSquareTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Calculating square of 9, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Completed CalcSquareTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Started CalcSquareAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Calculating square of 9, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Running Future for CalcSquareAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Completed Future for CalcSquareAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx&quot;
	at com.natpryce.hamkrest.assertion.AssertKt.assertThat(assert.kt:19)
	at com.natpryce.hamkrest.assertion.AssertKt.assertThat$default(assert.kt:16)
	at mycorda.app.tasks.TasksSpec$1$3$2.invoke(TasksSpec.kt:81)
	at mycorda.app.tasks.TasksSpec$1$3$2.invoke(TasksSpec.kt:22)
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(Scopes.kt:92)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:28)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:15)
	at org.spekframework.spek2.runtime.AbstractRuntime.execute(SpekRuntime.kt:46)
	at org.spekframework.spek2.junit.SpekTestEngine.execute(SpekTestEngine.kt:94)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.junit.platform.runner.JUnitPlatform.run(JUnitPlatform.java:133)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
</pre>
</span>
</div>
<div class="test">
<a name="executing ExceptionGeneratingAsyncTask via executor"></a>
<h3 class="failures">executing ExceptionGeneratingAsyncTask via executor</h3>
<span class="code">
<pre>java.lang.AssertionError: expected: a value that is equal to &quot;level=INFO, message=Started ExceptionGeneratingAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Message is 'Here is the exception', taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Running Future for ExceptionGeneratingAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=ExecutionException: java.lang.RuntimeException: Here is the exception, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=ERROR, message=Future Failed for ExceptionGeneratingAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx&quot;
but was: &quot;level=INFO, message=Started CalcSquareTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Calculating square of 9, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Completed CalcSquareTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Started CalcSquareAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Calculating square of 9, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Running Future for CalcSquareAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Completed Future for CalcSquareAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Started ExceptionGeneratingAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Message is 'Here is the exception', taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=Running Future for ExceptionGeneratingAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=INFO, message=ExecutionException: java.lang.RuntimeException: Here is the exception, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx
level=ERROR, message=Future Failed for ExceptionGeneratingAsyncTask, taskId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx&quot;
	at com.natpryce.hamkrest.assertion.AssertKt.assertThat(assert.kt:19)
	at com.natpryce.hamkrest.assertion.AssertKt.assertThat$default(assert.kt:16)
	at mycorda.app.tasks.TasksSpec$1$3$3.invoke(TasksSpec.kt:110)
	at mycorda.app.tasks.TasksSpec$1$3$3.invoke(TasksSpec.kt:22)
	at org.spekframework.spek2.runtime.scope.TestScopeImpl.execute(Scopes.kt:92)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:28)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:31)
	at org.spekframework.spek2.runtime.Executor.execute(Executor.kt:15)
	at org.spekframework.spek2.runtime.AbstractRuntime.execute(SpekRuntime.kt:46)
	at org.spekframework.spek2.junit.SpekTestEngine.execute(SpekTestEngine.kt:94)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
	at org.junit.platform.runner.JUnitPlatform.run(JUnitPlatform.java:133)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)
</pre>
</span>
</div>
</div>
<div id="tab1" class="tab">
<h2>Tests</h2>
<table>
<thead>
<tr>
<th>Test</th>
<th>Duration</th>
<th>Result</th>
</tr>
</thead>
<tr>
<td class="success">executing CalcSquareAsyncTask directly</td>
<td class="success">1.006s</td>
<td class="success">passed</td>
</tr>
<tr>
<td class="failures">executing CalcSquareAsyncTask via executor</td>
<td class="failures">1.021s</td>
<td class="failures">failed</td>
</tr>
<tr>
<td class="failures">executing ExceptionGeneratingAsyncTask via executor</td>
<td class="failures">0.007s</td>
<td class="failures">failed</td>
</tr>
</table>
</div>
<div id="tab2" class="tab">
<h2>Standard output</h2>
<span class="code">
<pre>need to cler out thr buffrr
INFO - Calculating square of 9
need to cler out thr buffrr
need to cler out thr buffrr
</pre>
</span>
</div>
</div>
<div id="footer">
<p>
<div>
<label class="hidden" id="label-for-line-wrapping-toggle" for="line-wrapping-toggle">Wrap lines
<input id="line-wrapping-toggle" type="checkbox" autocomplete="off"/>
</label>
</div>Generated by 
<a href="http://www.gradle.org">Gradle 5.6.4</a> at 21-May-2021 11:19:46</p>
</div>
</div>
</body>
</html>
